### ISSUE TITLE
Time aggregation and line plots

### ISSUE THREAD

**Issue by Rowanmh** [atomicateam/atomica#359]
With the use of t_bins to aggregate over time, the tvec is set to the end of the aggregated time. E.g. if aggregating with t_bins = 1, the aggregated value with the tvec of 2017 would correspond to the previous year of values from 1 Jan to 31 Dec 2016. This is a bit counter-intuitive in this typical use case for time aggregation, consider if it should be changed.

https://docs.atomica.tools/en/master/examples/Plotting.html#Time-aggregation-options

E.g. ` d = at.PlotData(results, outputs=plot_outputs, pops=plot_pops, pop_aggregation=pop_aggregation, t_bins=t_bins)
figs = at.plot_series(d, axis='results', plot_type='line')`

Adding in `        if t_bins is not None:
            for series in d.series:
                series.tvec -= t_bins` before plotting the series makes it display in "corrected" time steps so that the aggregated values over 2016 on the y-axis are displayed against 2016 on the x-axis rather than 2017, but there may (?) be other use cases where the current behaviour is equally logical and appropriate.

**Comment by Rowanmh** [comment]
There seems to be a definite issue here, discovered by accidentally plotting a flow rate parameter against a non-flow rate parameter with 5 year time bins, and getting an error because they had different `tvec` values (e.g. uPdeath:flow v uPdeath).

For a model run from 2010 to 2030

The flow rate parameter had tvec values of 2015, 2020, 2025, 2030

The non-flow rate parameter had tvec values of 2012.5, 2017.5, 2022.5, 2027.5, e.g. at the midpoints of each time bin.

The latter behaviour should probably be the case for all time aggregation?

**Comment by RomeshA** [comment]
@Rowanmh The different behaviour does seem to be a design choice - the time values are being set depending on whether the accumulation method is 'integrate' or 'average' where the upper edge is used for integration, and the midpoint is used for averaging. I don't recall the rationale for that choice though. Otherwise, you mentioned whether it should be assigned the lower bin edge rather than the upper edge (so that integrating from 2016 to 2017 is reported as 2016 rather than 2017). Let me know what you'd like to go with (I have a slight preference for using the midpoint for everything, I think that'll be simpler and more consistent generally)

**Comment by Rowanmh** [comment]
I think using the midpoint for everything would be the best solution for consistency too!
