### ISSUE TITLE
Review dependencies

### ISSUE THREAD

**Issue by Rowanmh** [atomicateam/atomica#374]
Reported that the following packages were required to run atomica analyses (could have been required from elsewhere):
pandoc
sphinx>=1.8
psutil
pandas
openpyxl
networkx
tqdm

The following packages were in requirements, but may not have actually been necessary (could be deprecated?):
enums

**Comment by RomeshA** [comment]
@Rowanmh to revisit this, was there a proposed action for this like moving something from `requirements.txt` to `setup.py`? Just unsure what the actual problem was e.g. did the user need to manually install those packages?

**Comment by Rowanmh** [comment]
@RomeshA yes, they needed to manually install those packages, but if they're necessary they should happen with setup.py I think (not a major hassle, of course)?

With enums they got all sorts of errors trying to install the package, but everything worked anyway I forget what it was but it looked like something that may have been replaced in necessity by a different way of doing things.

**Comment by RomeshA** [comment]
We probably should add some to `setup.py` like `networkx` but they should get picked up as dependencies when installing sciris and atomica because otherwise the automated tests would fail...and some of those like `openpyxl`, `tqdm`, `pandas`, `psutil` are already present in `setup.py` in Sciris or Atomica. So I wonder if somehow `setup.py` wasn't used?

It would also be great if there was any additional information on `pandoc` and `sphinx` because those are in `requirements.txt` but should only really be needed in order to compile the documentation, so I'd be curious what other tasks hit that dependency

**Comment by cliffckerr** [comment]
My understanding is that best practice is to list packages directly (and only directly) imported by by `atomica`...if you list `networkx`, say, because it's required by `pandas` but then the `pandas` requirements change, you'll end up with an unused dependency. Not the end of the world, but also no reason to do it...

**Comment by RomeshA** [comment]
This is probably OK now with the automated tests including checking dependencies. If there are any dependency issues, they aren't being picked up by the current test suite so we would need to add additional test(s) as well as updating dependencies. So closing this issue, but can open a new one if a specific problem comes up
