### ISSUE TITLE
Initialization of characteristics with a denominator and a setup weight

### ISSUE THREAD

**Issue by Rowanmh** [atomicateam/atomica#433]
`P = at.Project(framework =..., databook = ...)`
`P.run_sim()`

[Optima MNCH - fetal development framework_20200301.xlsx](https://github.com/atomicateam/atomica/files/6315547/Optima.MNCH.-.fetal.development.framework_20200301.xlsx)
[Optima MNCH - fetal development databook_20210412.xlsx](https://github.com/atomicateam/atomica/files/6315549/Optima.MNCH.-.fetal.development.databook_20210412.xlsx)

If a characteristic has:
1. A non-zero setup weight
2. A denominator
3. A databook entry

An error will be generated (as with `pregnant_1` in the example files above)

This appears to happen in `model.py` line 1857:
```if isinstance(obj, Characteristic):
                if obj.denominator is not None:
                    denom_par = parset.pars[obj.denominator.name]
                    b[i] *= denom_par.interpolate(t_init, pop_name=self.name)[0] * denom_par.y_factor[self.name] * denom_par.meta_y_factor
```

Atomica assumes that the denominator can be found in the parset, but as a compartment or characteristic this will never be the case - characteristics and compartments are not in the parset at all (?)

Maybe this was a design change as in class ParameterSet:
```
self.pars = sc.odict()  # : Stores the Parameter instances contained by this ParameterSet associated with framework comps, characs, and parameters
```
Although it only stores parameters?

**Comment by RomeshA** [comment]
Compartments and characteristics that are in the databook do appear in the parset (terminology isn't great for legacy reasons, but `parameters.Parameter` includes characteristics and compartments that appear in the databook) but the issue here is the initialization algorithm is based on solving a matrix equation of the form `b = Ax` where `b` are the input characteristic or compartment values in the databook/parset, and `x` is the values of the actual compartments. This requires that the target values are a linear combination of the compartments, but in the case where there are characteristic denominators, I think it's the case that if a characteristic has a characteristic with a denominator as its own denominator, the relationship between the compartment values and the characteristic values can become a nonlinear combination of the compartments which can't be solved with that simple matrix equation. To avoid this issue, characteristic denominators are pre-multiplied by the denominator prior to constructing the matrix equation, but this means that the denominator for the characteristics must appear in the databook (it's also potentially inconsistent with how the solution works, because normally if the characteristics disagree, least squares is used to solve it, but when the pre-multiplication takes place, it assumes the denominator value is exactly what was entered in the databook, which might not end up being the same as the actually calculated value - but that's a question for another day!) 

It looks like in this framework the initialization is all meant to be zero though, in which case those characteristics aren't useful/necessary for initialization anyway? In that case, the easiest solution might be to just enter a setup weight of 0 for those characteristics, in which case they will just be skipped entirely
